---
copyright: '2018 Luuk Verhoeven - LdesignMedia.nl / MoodleFreak.com <luuk@ldesignmedia.nl>'
component: mod_gcanvas
release: 0.1.0
version: 2018100800
requires: 2018051700
maturity: MATURITY_ALPHA
name: Canvas Game
mod_features:
  gradebook: false
  file_area: true
  navigation: true
  backup_moodle2:
    settingslib: false
features:
  install: true
  uninstall: true
  settings: true
  readme: true
  license: true
  upgrade: true
  upgradelib: false
